### ISSUE TITLE
Join/Leave logs and Server Status

### ISSUE THREAD

**Issue by LilSadPanda** [Abhijith4124/Ahhh-Bot#16]
After a few recent updates, the bot does not notify when a user Join/Leave the server.

Scenario 1:

Player connected to server then starting the bot, It will log that everyone left the server,

Scenario 2:

When bot is online, and players connect it will not log Join or Leave

**Comment by zensi-dev** [comment]
Are you using the latest version? This was a bug earlier but it has been resolved a while ago.

**Comment by LilSadPanda** [comment]
Hi @Abhijith4124,

Thanks for getting back to me, I tried with a fresh clone and the issue still exists. My Palworld server is running on windows, All ports are open. Other commands such as broadcast works.

It seems when whitelist is enabled it works, but if whitelist is disabled it does not send the Join/Leave logs

**Comment by Blacky0316** [comment]
> Hi @Abhijith4124,
> 
> Thanks for getting back to me, I tried with a fresh clone and the issue still exists. My Palworld server is running on windows, All ports are open. Other commands such as broadcast works.
> 
> It seems when whitelist is enabled it works, but if whitelist is disabled it does not send the Join/Leave logs

The bot is only for whitelist use, why else should you use it?

**Comment by LilSadPanda** [comment]
HI @Blacky0316

I'm not with you on that one, Whitelist is only one of the multiple features.

```
Ahhh Bot - Palworld Discord Bot | Whitelist | Join/Leave Messages | Automatic Roles and Announcement 
```

**Comment by zensi-dev** [comment]
> Hi @Abhijith4124,
> 
> Thanks for getting back to me, I tried with a fresh clone and the issue still exists. My Palworld server is running on windows, All ports are open. Other commands such as broadcast works.
> 
> It seems when whitelist is enabled it works, but if whitelist is disabled it does not send the Join/Leave logs

It should work without the whitelist enabled as well... Will look into it

**Comment by doublee313** [comment]
Same here. I just installed it and it won't do much. I don't need the whitelist options as well.

**Comment by zensi-dev** [comment]
Thanks for letting me know about this issue. Should be fixed in the [Latest Release](https://github.com/Abhijith4124/Ahhh-Bot/releases/tag/v1.2).
